# Generated by Django 5.2.8 on 2026-04-02 13:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('external_model_id', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fine_tuned', models.BooleanField(default=False)),
                ('is_macedonian_optimized', models.BooleanField(default=False)),
                ('supports_temperature', models.BooleanField(default=False)),
                ('supports_top_p', models.BooleanField(default=False)),
                ('supports_top_k', models.BooleanField(default=False)),
                ('supports_frequency_penalty', models.BooleanField(default=False)),
                ('supports_presence_penalty', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('api_base_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('judge', 'Judge')], max_length=32)),
                ('name', models.CharField(max_length=150)),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['agent_type', 'name', '-created_at'],
                'indexes': [models.Index(fields=['agent_type', 'is_active'], name='llm_arena_a_agent_t_96f308_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('agent_type',), name='unique_active_agent_prompt_per_type')],
            },
        ),
        migrations.CreateModel(
            name='ArenaBattle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('awaiting_vote', 'Awaiting Vote'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arena_battles', to=settings.AUTH_USER_MODEL)),
                ('model_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arena_battles_as_model_a', to='llm_arena.llmmodel')),
                ('model_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arena_battles_as_model_b', to='llm_arena.llmmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turn_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='llm_arena.arenabattle')),
            ],
            options={
                'ordering': ['turn_number', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BattleResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('A', 'Answer A'), ('B', 'Answer B')], max_length=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('response_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('finish_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='llm_arena.arenaturn')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='BattleResponseImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('improved_response_text', models.TextField()),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='improvement', to='llm_arena.battleresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(choices=[('A', 'Answer A'), ('B', 'Answer B'), ('tie', 'Tie')], max_length=4)),
                ('feedback', models.TextField(blank=True)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='llm_arena.arenabattle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMJudgeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(choices=[('A', 'Answer A'), ('B', 'Answer B'), ('tie', 'Tie')], max_length=4)),
                ('reasoning', models.TextField()),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_judge_vote', to='llm_arena.arenabattle')),
                ('judge_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llm_judge_votes', to='llm_arena.llmmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='llm_arena.llmprovider'),
        ),
        migrations.AddIndex(
            model_name='arenaturn',
            index=models.Index(fields=['battle', 'turn_number'], name='llm_arena_a_battle__ed4993_idx'),
        ),
        migrations.AddIndex(
            model_name='arenaturn',
            index=models.Index(fields=['battle', 'status'], name='llm_arena_a_battle__e41956_idx'),
        ),
        migrations.AddConstraint(
            model_name='arenaturn',
            constraint=models.UniqueConstraint(fields=('battle', 'turn_number'), name='unique_battle_turn_number'),
        ),
        migrations.AddIndex(
            model_name='battleresponse',
            index=models.Index(fields=['turn', 'status'], name='llm_arena_b_turn_id_83d620_idx'),
        ),
        migrations.AddConstraint(
            model_name='battleresponse',
            constraint=models.UniqueConstraint(fields=('turn', 'slot'), name='unique_turn_response_slot'),
        ),
        migrations.AddIndex(
            model_name='battlevote',
            index=models.Index(fields=['choice'], name='llm_arena_b_choice_065123_idx'),
        ),
        migrations.AddIndex(
            model_name='llmjudgevote',
            index=models.Index(fields=['choice'], name='llm_arena_l_choice_d7f767_idx'),
        ),
        migrations.AddIndex(
            model_name='llmjudgevote',
            index=models.Index(fields=['judge_model'], name='llm_arena_l_judge_m_97224d_idx'),
        ),
        migrations.AddIndex(
            model_name='arenabattle',
            index=models.Index(fields=['user', 'created_at'], name='llm_arena_a_user_id_206781_idx'),
        ),
        migrations.AddIndex(
            model_name='arenabattle',
            index=models.Index(fields=['status'], name='llm_arena_a_status_04703d_idx'),
        ),
        migrations.AddIndex(
            model_name='arenabattle',
            index=models.Index(fields=['created_at'], name='llm_arena_a_created_74b75d_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['is_active'], name='llm_arena_l_is_acti_b4ef06_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['is_fine_tuned'], name='llm_arena_l_is_fine_817b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['is_macedonian_optimized'], name='llm_arena_l_is_mace_15125f_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['supports_temperature'], name='llm_arena_l_support_7b0d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['supports_top_p'], name='llm_arena_l_support_284c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['supports_top_k'], name='llm_arena_l_support_450b31_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['supports_frequency_penalty'], name='llm_arena_l_support_4a6a97_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['supports_presence_penalty'], name='llm_arena_l_support_e3740b_idx'),
        ),
        migrations.AddConstraint(
            model_name='llmmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'external_model_id'), name='unique_provider_external_model_id'),
        ),
    ]
