WELLNESS_SCORE_MIN = 0
WELLNESS_SCORE_MAX = 100
RECENT_ENTRY_LIMIT = 7
MAX_FUTURE_ENTRY_DAYS = 1

DEFAULT_SECRET_KEY = "django-insecure-local-wellness-dev-key"
DEFAULT_DEBUG = True
DEFAULT_ALLOWED_HOSTS = "localhost,127.0.0.1"
DEFAULT_DATABASE_NAME = "wellness_db"
DEFAULT_DATABASE_USER = "postgres"
DEFAULT_DATABASE_PASSWORD = "postgres"
DEFAULT_DATABASE_HOST = "localhost"
DEFAULT_DATABASE_PORT = "5432"
DEFAULT_FRONTEND_URL = "http://localhost:5173"
DEFAULT_OPENAI_API_KEY = ""
DEFAULT_OPENAI_MODEL = "gpt-4o-mini"
DEFAULT_TIME_ZONE = "Europe/Skopje"
